# Generated by Django 3.2 on 2021-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activity_activity2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('Organizer', models.CharField(max_length=50)),
                ('qualifications', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=3)),
                ('tel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Canyu',
            },
        ),
    ]
