# Generated by Django 3.2 on 2021-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_childimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/pictures/')),
            ],
            options={
                'db_table': 'Testimg',
            },
        ),
        migrations.RemoveField(
            model_name='child',
            name='img',
        ),
    ]
