# Generated by Django 3.2 on 2021-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210720_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dproject', models.CharField(max_length=50)),
                ('damount', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('dtel', models.CharField(max_length=50)),
                ('dtext', models.CharField(max_length=50)),
                ('dway', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'donate',
            },
        ),
        migrations.CreateModel(
            name='Sum1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Sum1',
            },
        ),
    ]
